import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/sessionWrapper";

const inter = Inter({ subsets: ["latin"], display: 'swap' });

export const metadata: Metadata = {
  title: "MyCon - 나만의 컨설턴트",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="ko">
        <body className={`${inter.className} bg-background text-text-primary`}>
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}