name: Sync to Synology NAS

on:
  push:
    branches:
      - master  # 'master' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git safe directory
        run: git config --global --add safe.directory /volume1/docker/nextjs15/eventlog

      - name: Debug SSH Key  # SSH 키가 정상적으로 전달되는지 확인
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l

      - name: Sync with Synology NAS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EXTERNAL_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222  # 외부 접속 포트
          script: |
            export PATH=$PATH:/usr/local/bin
            cd /volume1/docker/nextjs15/eventlog

            # SSH 디버깅 추가 (현재 사용자가 누구인지 확인)
            whoami
            ls -la ~/.ssh
            echo "$SSH_AUTH_SOCK"

            # GitHub에 SSH 방식으로 접근하기 위해 원격 URL 설정 (이미 설정되어 있다면 생략 가능)
            git remote set-url origin git@github.com:evenoahchoi/eventlog.git

            # 원격 저장소에서 최신 내용 가져오기 및 강제 동기화
            git fetch origin master
            git reset --hard origin/master
            git clean -fd

            npm install
            npm run build

            docker restart eventlog
